### ISSUE TITLE
Create basic web interface

### ISSUE THREAD

**Issue by tmwsnrx** [MG-5/esp-dfi-ignah#6]
# Web Interface

The ESP32 shall provide a minimal website for configuring settings like WLAN credentials in STA and AP mode, text to be displayed etc. For this purpose, a web frontend written using Angular will be created. Angular produces static HTML, JavaScript and CSS files the server on the ESP32 needs to provide alongside an API which is consumed by the frontend. This issue is only for creating the initial application that can be served without any real functionality.

## Tasks

- [x] Create new empty Angular project and remove starter content
- [x] Add Angular Material
- [x] Add mat-toolbar and sidenav
- [x] Add routing
- [x] Add dark mode
- [x] Integrate dist files into firmware and make them accessible
- [x] Add display mode settings
